FROM php:8.2-apache

# Instala dependencias del sistema y GD
RUN apt-get update && apt-get install -y \
    unzip curl git zip libzip-dev libonig-dev libxml2-dev \
    libpng-dev libjpeg-dev libfreetype6-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo pdo_mysql mbstring zip gd

# Habilita mod_rewrite para Laravel
RUN a2enmod rewrite

# Copia Composer desde imagen oficial
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Establece directorio de trabajo
WORKDIR /var/www/html

# Copia solo composer files primero para cache
COPY composer.json composer.lock ./

# Instala dependencias
RUN composer install --no-dev --no-scripts --optimize-autoloader --ignore-platform-reqs

# Copia el resto del proyecto
COPY . .

# Permisos para Laravel
RUN chown -R www-data:www-data storage bootstrap/cache

# Configura el document root en Apache
ENV APACHE_DOCUMENT_ROOT /var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf \
 && sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

EXPOSE 80

CMD ["apache2-foreground"]
